name: Nosso blog
description: Aqui é tudo nosso
meta_description: "Aqui é tudo nosso"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "pehescamander.github.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Nosotros"

# Disqus config
disqus-shortname: ""
